osx_image: xcode12.5
language: swift
os: osx
xcode_project: LightCalculatorPlus.xcodeproj
xcode_scheme: HCalculator
xcode_destination: platform=iOS Simulator,OS=14.5,name=iPhone 8

after_success:
 - bash <(curl -s https://codecov.io/bash)
